services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace/faststream-mq:cached
    working_dir: /workspace/faststream-mq
    network_mode: host
    environment:
      UV_PROJECT_ENVIRONMENT: /workspace/faststream-mq/.venv
      MQ_FILE_PATH: /opt/mqm
      LD_LIBRARY_PATH: /opt/mqm/lib64
